name: Build my extension

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build extension
        run: ./gradlew :src:en:theyiffgallery:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mi-extension-apk
          path: src/en/theyiffgallery/build/outputs/apk/**/*.apk
